# Generated by Django 5.2.4 on 2025-09-09 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0005_alter_phototype_options_photo_datetime_utc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the evidence.')),
                ('explanation', models.TextField(blank=True, help_text='A detailed explanation of the supporting evidence, auto-filled for photo clusters.')),
                ('email_quote', models.TextField(blank=True, help_text='A specific quote or excerpt from an email.', null=True)),
                ('allegation', models.ForeignKey(blank=True, help_text='The specific allegation this evidence supports or refutes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to=settings.AUTH_USER_MODEL)),
                ('linked_email', models.ForeignKey(blank=True, help_text='The specific email this quote is from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_quotes', to=settings.AUTH_USER_MODEL)),
                ('linked_photos', models.ManyToManyField(blank=True, help_text='A collection of photos related to this evidence.', related_name='evidence', to='photos.photo')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent event for this piece of evidence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SupportingEvidence.supportingevidence')),
            ],
            options={
                'verbose_name': 'Supporting Evidence',
                'verbose_name_plural': 'Supporting Evidences',
                'ordering': ['date'],
            },
        ),
    ]
