# Generated by Django 5.2.4 on 2025-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('photos', '0005_alter_phototype_options_photo_datetime_utc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingEvidenceLinkedPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'SupportingEvidence_supportingevidence_linked_photos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EventLinkedPhotos',
        ),
        migrations.AlterField(
            model_name='event',
            name='linked_photos',
            field=models.ManyToManyField(blank=True, help_text='A collection of photos related to this event.', related_name='events', through='events.SupportingEvidenceLinkedPhotos', to='photos.photo'),
        ),
    ]
