# Generated by Django 5.2.4 on 2025-11-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportingevidencelinkedphotos',
            options={'managed': False},
        ),
    ]
