# Generated by Django 5.2.4 on 2025-10-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportingEvidence', '0001_initial'),
        ('document_manager', '0005_documentnode_is_falsifiable_documentnode_is_true'),
        ('email_manager', '0005_quote'),
        ('photos', '0005_alter_phototype_options_photo_datetime_utc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingEvidenceLinkedPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'SupportingEvidence_supportingevidence_linked_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the event.')),
                ('explanation', models.TextField(blank=True, help_text='A detailed explanation of the event, auto-filled for photo clusters.')),
                ('email_quote', models.TextField(blank=True, help_text='A specific quote or excerpt from an email.', null=True)),
                ('allegation', models.ForeignKey(blank=True, help_text='The specific allegation this event supports or refutes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='document_manager.documentnode')),
                ('linked_email', models.ForeignKey(blank=True, help_text='The specific email this quote is from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='email_manager.email')),
                ('linked_photos', models.ManyToManyField(blank=True, help_text='A collection of photos related to this event.', related_name='events', through='SupportingEvidence.SupportingEvidenceLinkedPhotos', to='photos.photo')),
                ('parent', models.ForeignKey(blank=True, help_text='The parent event for this piece of evidence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SupportingEvidence.event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'SupportingEvidence_supportingevidence',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='SupportingEvidence',
        ),
    ]
