# Generated by Django 5.2.4 on 2026-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='debut',
            field=models.DateTimeField(blank=True, help_text="Début de l'événement. Initialisé sur la première photographie liée, mais modifiable : les photographies bornent l'événement par le bas, elles ne le définissent pas.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fin',
            field=models.DateTimeField(blank=True, help_text="Fin de l'événement. Même convention que `debut`.", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='explanation',
            field=models.TextField(blank=True, help_text="Description de l'événement, en français, SANS horodatage : les bornes vivent dans `debut` et `fin`."),
        ),
    ]
