# Generated by Django 5.2.4 on 2025-08-23 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the PDF document.', max_length=255)),
                ('file', models.FileField(help_text='The uploaded PDF file.', upload_to='pdf_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the document was uploaded.')),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
