# Generated by Django 5.2.4 on 2025-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='document_date',
            field=models.DateField(blank=True, help_text='The date of the document, if applicable.', null=True),
        ),
    ]
