# Generated by Django 5.2.4 on 2025-08-26 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0002_pdfdocument_document_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the document type (e.g., 'Mémoire de Marie-Josée').", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'PDF Document Type',
                'verbose_name_plural': 'PDF Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'ordering': ['-document_date'], 'verbose_name': 'PDF Document', 'verbose_name_plural': 'PDF Documents'},
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='The type or category of this PDF document.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_manager.pdfdocumenttype'),
        ),
    ]
