# Generated by Django 5.2.4 on 2025-10-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0003_pdfdocumenttype_alter_pdfdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('page_number', models.PositiveIntegerField(help_text='The page number where the quote can be found.')),
                ('quote_location_details', models.CharField(blank=True, help_text="Optional details to locate the quote, e.g., 'Paragraph 3' or 'Header'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='pdf_manager.pdfdocument')),
            ],
            options={
                'verbose_name': 'PDF Quote',
                'verbose_name_plural': 'PDF Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
