# Generated by Django 5.2.4 on 2025-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0004_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='full_sentence',
            field=models.TextField(blank=True),
        ),
    ]
