# Generated by Django 5.2.4 on 2026-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0004_pdfdocument_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='position_anchor',
            field=models.TextField(blank=True, default='', help_text='A verbatim fragment of the document, used only to place this quote in the text. Fill it in when quote_text is a reading of the document — a summary of table rows, say — rather than a passage copied out of it, and so cannot be found by searching for it. Never displayed.'),
        ),
    ]
