# Generated by Django 5.2.4 on 2025-10-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0005_quote_full_sentence'),
        ('protagonist_manager', '0002_remove_protagonist_email_protagonistemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The author of the document, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pdfs', to='protagonist_manager.protagonist'),
        ),
    ]
