# Generated by Django 5.2.4 on 2025-10-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0006_pdfdocument_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='full_sentence',
        ),
    ]
