# Generated by Django 5.2.4 on 2026-08-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0006_pdfdocument_note_pdfdocument_note_maj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='analyse',
            field=models.TextField(blank=True, default='', help_text='Analyse rédigée sur cette pièce, en HTML.'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='analyse_maj',
            field=models.DateTimeField(blank=True, help_text="Dernière écriture de l'analyse. NULL = jamais renseignée.", null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='analyse_source',
            field=models.CharField(blank=True, default='', help_text="Nom du fichier du corpus dont l'analyse est issue. Rend l'import rejouable et permet de comparer base et fichier.", max_length=255),
        ),
    ]
