# Generated by Django 5.2.4 on 2026-09-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0007_pdfdocument_analyse_pdfdocument_analyse_maj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfdocument',
            options={'ordering': ['-document_date', '-pk'], 'verbose_name': 'PDF Document', 'verbose_name_plural': 'PDF Documents'},
        ),
    ]
