# Generated by Django 5.2.4 on 2025-10-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_manager', '0005_documentnode_is_falsifiable_documentnode_is_true'),
        ('email_manager', '0006_remove_quote_perjury_elements_alter_email_dao_source_and_more'),
        ('events', '0001_initial'),
        ('pdf_manager', '0004_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrameNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Un titre descriptif pour ce dossier d'argumentation (ex: 'Preuve de l'implication parentale').", max_length=255)),
                ('resume', models.TextField(help_text='Le résumé expliquant comment les preuves assemblées forment un argument cohérent contre (ou pour) les allégations ciblées.')),
                ('type_argument', models.CharField(choices=[('CONTRADICTION', 'Vise à contredire les allégations'), ('SUPPORT', 'Vise à supporter les allégations')], max_length=20)),
                ('allegations_ciblees', models.ManyToManyField(help_text='Les allégations spécifiques ciblées par cet argumentaire.', related_name='trames_narratives', to='document_manager.documentnode')),
                ('citations_courriel', models.ManyToManyField(blank=True, related_name='trames_narratives', to='email_manager.quote')),
                ('citations_pdf', models.ManyToManyField(blank=True, related_name='trames_narratives', to='pdf_manager.quote')),
                ('evenements', models.ManyToManyField(blank=True, related_name='trames_narratives', to='events.event')),
            ],
            options={
                'verbose_name': 'Trame Narrative',
                'verbose_name_plural': 'Trames Narratives',
            },
        ),
    ]
