# Generated by Django 5.2.4 on 2025-10-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0001_initial'),
        ('photos', '0007_photodocument_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramenarrative',
            name='photo_documents',
            field=models.ManyToManyField(blank=True, related_name='trames_narratives', to='photos.photodocument'),
        ),
    ]
