# Generated by Django 5.2.4 on 2026-08-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0008_tramenarrative_ai_analysis_json_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('document_manager', '0015_schemaniveaux_document_schema_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fenetre_debut', models.DateField(blank=True, null=True)),
                ('fenetre_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cibles', models.ManyToManyField(blank=True, help_text='Les allégations que cet axe conteste, dans un acte REPRODUCED.', related_name='axes_contestataires', to='document_manager.statement')),
            ],
            options={
                'verbose_name': 'Axe',
                'verbose_name_plural': 'Axes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('enonce', models.TextField()),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faits', to='argument_manager.axe')),
            ],
            options={
                'verbose_name': 'Fait',
                'verbose_name_plural': 'Faits',
                'ordering': ['axe', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='AppuiFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('ATTESTATION', 'Atteste directement un fait daté'), ('CADRE', 'Établit la structure ou le contexte'), ('INFERENCE', "N'établit pas le fait, le présuppose"), ('VERIFICATION', 'Confirmation postérieure par un tiers'), ('ILLUSTRATION', 'À titre informatif — ne porte aucun fait')], default='ATTESTATION', max_length=14)),
                ('note', models.TextField(blank=True, help_text='Pourquoi cette pièce soutient ce fait, et à quel titre.')),
                ('content_type', models.ForeignKey(help_text='Modèle de la pièce : Email, Event, PDFDocument, PhotoDocument…', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('fait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appuis', to='argument_manager.fait')),
            ],
            options={
                'verbose_name': 'Appui',
                'verbose_name_plural': 'Appuis',
                'ordering': ['fait', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('fait', 'content_type', 'object_id'), name='appui_unique_par_fait')],
            },
        ),
    ]
