# Generated by Django 5.2.4 on 2026-08-14 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argument_manager', '0010_fait_vers_statement'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RattachementAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, help_text="Pourquoi cette pièce concerne cet axe, si ce n'est pas évident.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rattachements', to='argument_manager.axe')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Rattachement à un axe',
                'verbose_name_plural': 'Rattachements à un axe',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='argument_ma_content_ec0651_idx')],
                'constraints': [models.UniqueConstraint(fields=('axe', 'content_type', 'object_id'), name='rattachement_axe_unique')],
            },
        ),
    ]
