# Generated by Django 5.2.4 on 2025-07-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text="The start date of the evidence's relevance.")),
                ('end_date', models.DateField(blank=True, help_text="The end date of the evidence's relevance (optional, for ranges).", null=True)),
                ('description', models.CharField(help_text='A short description of the supporting evidence.', max_length=255)),
                ('explanation', models.TextField(help_text='A detailed explanation of the supporting evidence.')),
                ('object_id', models.PositiveIntegerField(help_text='The primary key (ID) of the related object.')),
                ('content_type', models.ForeignKey(help_text='The type of object this evidence refers to (e.g., Photo, Email, PDF).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Supporting Evidence',
                'verbose_name_plural': 'Supporting Evidences',
                'ordering': ['start_date', 'id'],
            },
        ),
    ]
