# Generated by Django 5.2.4 on 2025-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportingEvidence', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingevidence',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='supportingevidence',
            name='object_id',
        ),
        migrations.AddField(
            model_name='supportingevidence',
            name='linked_photos',
            field=models.ManyToManyField(blank=True, help_text='A collection of photos related to this evidence.', related_name='evidence_as_photo', to='photos.photo'),
        ),
    ]
