# Generated by Django 5.2.4 on 2026-08-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0008_producedexhibit_public_url'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauDepotJuillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote', models.CharField(db_index=True, help_text="Cote complète, telle qu'elle serait citée : « P-43 » ou « P-43.7 ».", max_length=20, unique=True)),
                ('cote_racine', models.CharField(db_index=True, help_text='Cote de la pièce mère : « P-43 », pour P-43.7 comme pour P-43.', max_length=20)),
                ('rang', models.PositiveIntegerField(help_text='Partie numérique de la cote racine, pour le tri (43).')),
                ('sous_rang', models.PositiveIntegerField(blank=True, help_text='Rang dans la liasse (7), ou NULL si la pièce est simple.', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, help_text='Type tel que résolu depuis le bordereau : email, thread, pdf, event, photo, photodoc, chatsequence, document.', max_length=30)),
                ('source_ref', models.CharField(blank=True, help_text="Colonne « Fichier d'appui » du bordereau, brute.", max_length=500)),
                ('date_libelle', models.CharField(blank=True, help_text='Colonne « Date », telle quelle : « 16 juin–16 août 2013 ».', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Colonne « Pièce » du bordereau déposé.')),
                ('resolu', models.BooleanField(default=False, help_text='True si content_object a pu être rattaché à un objet existant.')),
                ('note', models.TextField(blank=True, help_text="Motif de non-résolution ou remarque d'import.")),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Modèle de la pièce : Email, EmailThread, PDFDocument, Event, Photo, PhotoDocument, ChatSequence, Document.', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Bordereau — dépôt du 24 juillet 2026',
                'verbose_name_plural': 'Bordereau — dépôt du 24 juillet 2026',
                'ordering': ['rang', 'sous_rang'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='case_manage_content_afe707_idx'), models.Index(fields=['cote_racine'], name='case_manage_cote_ra_41f633_idx')],
                'constraints': [models.UniqueConstraint(fields=('cote_racine', 'sous_rang'), name='bordereau_juillet_souscote_unique')],
            },
        ),
    ]
