# Generated by Django 5.2.4 on 2026-08-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0009_bordereaudepotjuillet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordereaudepotjuillet',
            name='cote',
            field=models.CharField(blank=True, db_index=True, help_text='Cote de juillet : « P-43 » ou « P-43.7 ». NULL si non déposée.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bordereaudepotjuillet',
            name='cote_racine',
            field=models.CharField(blank=True, db_index=True, help_text='Cote de la pièce mère : « P-43 », pour P-43.7 comme pour P-43.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bordereaudepotjuillet',
            name='rang',
            field=models.PositiveIntegerField(blank=True, help_text='Partie numérique de la cote racine, pour le tri (43).', null=True),
        ),
    ]
