# Generated by Django 5.2.4 on 2026-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0010_alter_bordereaudepotjuillet_cote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereaudepotjuillet',
            name='atemporel',
            field=models.BooleanField(default=False, help_text="La pièce n'a pas de date PAR NATURE — capture d'un fait permanent, grille horaire, définition. À distinguer d'une date simplement manquante : celle-ci s'ajoutera, l'autre jamais. Une pièce atemporelle se range en fin de cotation chronologique sans qu'on la signale comme à corriger."),
        ),
    ]
