# Generated by Django 5.2.4 on 2026-08-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0011_bordereaudepotjuillet_atemporel'),
        ('document_manager', '0015_schemaniveaux_document_schema_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppuiDepotJuillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote_citee', models.CharField(help_text="La cote telle qu'ÉCRITE dans le paragraphe : « P-48.1 », ou « P-43 » lorsque le texte invoque la liasse en bloc.", max_length=20)),
                ('via_liasse', models.BooleanField(default=False, help_text="True si la ligne provient du développement d'une cote racine. Le paragraphe n'a pas nommé cette pièce : il a nommé sa liasse.")),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entree', models.ForeignKey(help_text="La ligne du bordereau, c'est-à-dire la pièce sous sa cote.", on_delete=django.db.models.deletion.PROTECT, related_name='appuis_depot', to='case_manager.bordereaudepotjuillet')),
                ('statement', models.ForeignKey(help_text='Le paragraphe de la demande déposée qui invoque la pièce.', on_delete=django.db.models.deletion.CASCADE, related_name='appuis_depot', to='document_manager.statement')),
            ],
            options={
                'verbose_name': 'Appui — dépôt du 24 juillet 2026',
                'verbose_name_plural': 'Appuis — dépôt du 24 juillet 2026',
                'ordering': ['statement', 'entree'],
                'indexes': [models.Index(fields=['entree'], name='case_manage_entree__975762_idx'), models.Index(fields=['statement'], name='case_manage_stateme_51bdda_idx')],
                'constraints': [models.UniqueConstraint(fields=('statement', 'entree'), name='appui_depot_unique')],
            },
        ),
    ]
