# Generated by Django 5.2.4 on 2026-08-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_manager', '0012_appuidepotjuillet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuidepotjuillet',
            name='precision',
            field=models.ForeignKey(blank=True, help_text="Le passage précis sur lequel ce paragraphe s'appuie, quand il est identifiable. `entree` continue de dire ce que juillet a plaidé — « P-98 » ; celle-ci dit sur quoi, dans P-98, le paragraphe repose réellement.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appuis_precision', to='case_manager.bordereaudepotjuillet'),
        ),
        migrations.AddField(
            model_name='bordereaudepotjuillet',
            name='cote_pont',
            field=models.CharField(blank=True, db_index=True, help_text="Cote de travail : « P-98 » reprise de juillet, ou « P-98.1 » pour un passage précis. NULL tant que la pièce n'entre pas au pont.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bordereaudepotjuillet',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='La pièce dont cette ligne précise un passage. NULL pour une pièce entière.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precisions', to='case_manager.bordereaudepotjuillet'),
        ),
        migrations.AddField(
            model_name='bordereaudepotjuillet',
            name='rang_precision',
            field=models.PositiveIntegerField(blank=True, help_text='Rang du passage sous sa pièce mère (le .1 de P-98.1).', null=True),
        ),
    ]
