# Generated by Django 5.2.4 on 2025-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Absolute path to the image file.', max_length=500, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('folder_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('created_on_disk', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('image_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_original', models.DateTimeField(blank=True, null=True)),
                ('iso_speed', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('exposure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('f_number', models.FloatField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('lens_model', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_width', models.IntegerField(blank=True, null=True)),
                ('raw_height', models.IntegerField(blank=True, null=True)),
                ('color_depth', models.IntegerField(blank=True, null=True)),
                ('num_colors', models.IntegerField(blank=True, null=True)),
                ('cfa_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_altitude', models.FloatField(blank=True, null=True)),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True)),
                ('all_metadata_json', models.JSONField(blank=True, default=dict, null=True)),
                ('date_folder', models.DateField(blank=True, help_text='Date extracted from the folder name (YYYY-MM-DD)', null=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['datetime_original'],
            },
        ),
    ]
