# Generated by Django 5.2.4 on 2025-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, help_text='The actual image file.', null=True, upload_to='photos/'),
        ),
    ]
