# Generated by Django 5.2.4 on 2025-08-28 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the photo type (e.g., 'Events').", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Photo Type',
                'verbose_name_plural': 'Photo Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(blank=True, help_text='The type or category of this photo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.phototype'),
        ),
    ]
