# Generated by Django 5.2.4 on 2026-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photodocument_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodocument',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Note de l'utilisateur sur cette pièce, en HTML. Jamais écrite par un import."),
        ),
        migrations.AddField(
            model_name='photodocument',
            name='note_maj',
            field=models.DateTimeField(blank=True, help_text='Dernière écriture de la note. NULL = jamais renseignée.', null=True),
        ),
    ]
