# Generated by Django 5.2.4 on 2025-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_phototype_photo_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.CharField(help_text='Absolute path to the image file.', max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='folder_path',
            field=models.CharField(help_text='Path to the folder containing the image file.', max_length=500),
        ),
    ]
