# Generated by Django 5.2.4 on 2025-09-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_file_path_alter_photo_folder_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototype',
            options={},
        ),
        migrations.AddField(
            model_name='photo',
            name='datetime_utc',
            field=models.DateTimeField(blank=True, help_text='The timezone-aware UTC datetime, typically from an XMP sidecar file.', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_folder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='datetime_original',
            field=models.DateTimeField(blank=True, help_text="The naive datetime from the camera's EXIF data.", null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='folder_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.phototype'),
        ),
        migrations.AlterField(
            model_name='phototype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
