# Generated by Django 5.2.4 on 2025-10-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_phototype_options_photo_datetime_utc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the document.', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional notes or a summary of the document's content.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(help_text='The photos that make up this document.', related_name='photo_documents', to='photos.photo')),
            ],
            options={
                'verbose_name': 'Photo Document',
                'verbose_name_plural': 'Photo Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
