# Generated by Django 5.2.4 on 2025-10-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photodocument'),
        ('protagonist_manager', '0002_remove_protagonist_email_protagonistemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodocument',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The author of the document, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_photo_documents', to='protagonist_manager.protagonist'),
        ),
    ]
