# Generated by Django 5.2.4 on 2025-07-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.IntegerField(help_text="Valeur 'gauche' pour le parcours ensembliste imbriqué (nested set).")),
                ('rgt', models.IntegerField(help_text="Valeur 'droite' pour le parcours ensembliste imbriqué (nested set).")),
                ('item', models.CharField(help_text="Nom court ou identifiant du nœud (ex: 'requete', 'chapitre').", max_length=255)),
                ('text', models.TextField(blank=True, help_text='Le contenu textuel de ce nœud de document.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Le nœud parent de ce document. Laissez vide pour un nœud racine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='document_manager.documentnode')),
            ],
            options={
                'verbose_name': 'Nœud de Document',
                'verbose_name_plural': 'Nœuds de Documents',
                'ordering': ['lft'],
            },
        ),
    ]
