# Generated by Django 5.2.4 on 2025-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_documentnode_depth_documentnode_node_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentnode',
            options={'verbose_name': 'Nœud de Document', 'verbose_name_plural': 'Nœuds de Documents'},
        ),
        migrations.AlterUniqueTogether(
            name='documentnode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentnode',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentnode',
            name='path',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentnode',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='documentnode',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='documentnode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='documentnode',
            name='rgt',
        ),
    ]
