# Generated by Django 5.2.4 on 2025-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0003_alter_documentnode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnode',
            name='item',
            field=models.CharField(help_text="Nom court ou titre du nœud (ex: 'requete', 'chapitre').", max_length=555),
        ),
    ]
