# Generated by Django 5.2.4 on 2025-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_alter_documentnode_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnode',
            name='is_falsifiable',
            field=models.BooleanField(blank=True, default=None, help_text="Indique si une affirmation (qui est fausse) est falsifiable. Non applicable si l'affirmation est vraie.", null=True),
        ),
        migrations.AddField(
            model_name='documentnode',
            name='is_true',
            field=models.BooleanField(default=True, help_text="Indique si l'affirmation est considérée comme vraie."),
        ),
    ]
