# Generated by Django 5.2.4 on 2026-08-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0014_librarynode_is_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaNiveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schéma de niveaux',
                'verbose_name_plural': 'Schémas de niveaux',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='schema',
            field=models.ForeignKey(blank=True, help_text="Règle d'interprétation des niveaux. Laisser vide tant que la forme du document n'est pas arrêtée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='document_manager.schemaniveaux'),
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profondeur', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('RACINE', 'Racine du document'), ('SECTION', 'Section (§)'), ('SOUS_SECTION', 'Sous-section'), ('THEME', 'Thème'), ('SOUS_THEME', 'Sous-thème'), ('CHAPEAU', 'Chapeau (annonce ses enfants)'), ('PARAGRAPHE', 'Paragraphe numérotable'), ('SOUS_ITEM', "Sous-item d'un paragraphe"), ('ENUMERATION', "Élément d'énumération"), ('LIBRE', 'Contenu libre, non numéroté')], max_length=20)),
                ('format_numero', models.CharField(choices=[('AUCUN', 'Pas de numéro'), ('DECIMAL', '1, 2, 3'), ('ROMAIN_MAJ', 'I, II, III'), ('LETTRE_MAJ', 'A, B, C'), ('LETTRE_MIN', 'a), b), c)')], default='AUCUN', max_length=12)),
                ('portee', models.CharField(choices=[('AUCUNE', 'Sans objet'), ('DOCUMENT', 'Continue sur tout le document'), ('PARENT', 'Repart sous chaque parent')], default='AUCUNE', max_length=12)),
                ('libelle', models.CharField(blank=True, help_text='Nom lisible, pour les rapports.', max_length=120)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='document_manager.schemaniveaux')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['schema', 'profondeur'],
                'constraints': [models.UniqueConstraint(fields=('schema', 'profondeur'), name='niveau_unique_par_schema')],
            },
        ),
    ]
