# Generated by Django 5.2.4 on 2025-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('recipients_to', models.TextField(blank=True, help_text="Comma-separated 'To' recipients", null=True)),
                ('recipients_cc', models.TextField(blank=True, help_text="Comma-separated 'Cc' recipients", null=True)),
                ('recipients_bcc', models.TextField(blank=True, help_text="Comma-separated 'Bcc' recipients", null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('body_plain_text', models.TextField(blank=True, null=True)),
                ('eml_file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Email',
                'verbose_name_plural': 'Saved Emails',
                'ordering': ['-date_sent'],
            },
        ),
    ]
