# Generated by Django 5.2.4 on 2025-07-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0001_initial'),
        ('protagonist_manager', '0002_remove_protagonist_email_protagonistemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedemail',
            name='protagonist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_emails', to='protagonist_manager.protagonist'),
        ),
    ]
