# Generated by Django 5.2.4 on 2025-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0002_savedemail_protagonist'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedemail',
            name='dao_source',
            field=models.CharField(blank=True, help_text='The source DAO used to acquire this email (e.g., Gmail, EML Upload).', max_length=50, null=True),
        ),
    ]
