# Generated by Django 5.2.4 on 2025-10-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0005_documentnode_is_falsifiable_documentnode_is_true'),
        ('email_manager', '0004_emailthread_email_delete_savedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('full_sentence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='email_manager.email')),
                ('perjury_elements', models.ManyToManyField(limit_choices_to={'is_falsifiable': True, 'is_true': False}, related_name='quotes', to='document_manager.documentnode')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
