# Generated by Django 5.2.4 on 2026-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0005_email_analyse_email_analyse_maj_email_analyse_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Notes et consignes sur cette pièce, en HTML.'),
        ),
        migrations.AddField(
            model_name='email',
            name='note_maj',
            field=models.DateTimeField(blank=True, help_text='Dernière écriture de la note. NULL = jamais renseignée.', null=True),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Notes et consignes sur cette pièce, en HTML.'),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='note_maj',
            field=models.DateTimeField(blank=True, help_text='Dernière écriture de la note. NULL = jamais renseignée.', null=True),
        ),
    ]
