# Generated by Django 5.2.4 on 2025-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0005_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='perjury_elements',
        ),
        migrations.AlterField(
            model_name='email',
            name='dao_source',
            field=models.CharField(default='uploaded_eml', help_text='The source used to acquire this email (e.g., Gmail).', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='eml_file_path',
            field=models.CharField(default='path', max_length=1024),
            preserve_default=False,
        ),
    ]
