# Generated by Django 5.2.4 on 2025-10-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0006_remove_quote_perjury_elements_alter_email_dao_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='full_sentence',
        ),
    ]
