# Generated by Django 5.2.4 on 2026-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0006_email_note_email_note_maj_emailthread_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Note de l'utilisateur sur cette pièce, en HTML. Jamais écrite par un import."),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Note de l'utilisateur sur cette pièce, en HTML. Jamais écrite par un import."),
        ),
    ]
