# Generated by Django 5.2.4 on 2025-10-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_manager', '0007_remove_quote_full_sentence'),
        ('protagonist_manager', '0002_remove_protagonist_email_protagonistemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient_protagonists',
            field=models.ManyToManyField(blank=True, help_text='The protagonists who received this email.', related_name='received_emails', to='protagonist_manager.protagonist'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender_protagonist',
            field=models.ForeignKey(blank=True, help_text='The protagonist who sent this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='protagonist_manager.protagonist'),
        ),
    ]
