# Generated by Django 5.2.4 on 2025-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The protagonist's first name.", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="The protagonist's last name (optional).", max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text="The protagonist's email address (optional, must be unique if provided).", max_length=255, null=True, unique=True)),
                ('role', models.CharField(help_text="The role of the protagonist in the story (e.g., 'Hero', 'Villain', 'Sidekick').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protagonist',
                'verbose_name_plural': 'Protagonists',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
