# Generated by Django 5.2.4 on 2025-07-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protagonist_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protagonist',
            name='email',
        ),
        migrations.CreateModel(
            name='ProtagonistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='An email address for the protagonist.', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, help_text="e.g., 'Work', 'Personal', 'Old'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protagonist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='protagonist_manager.protagonist')),
            ],
            options={
                'verbose_name': 'Protagonist Email',
                'verbose_name_plural': 'Protagonist Emails',
                'ordering': ['email_address'],
            },
        ),
    ]
